# Define environment
dist: xenial # Ubuntu 16.04
language: bash

# Only build pushes to master branch
branches:
  only:
    - master

# Export variables as global
env:
  global:
    # Setting the version of terraform
    - tf_version=0.12.19

    # Setting terraform init CLI options - https://www.terraform.io/docs/commands/init.html
    - tf_init_cli_options=" -input=false"

    # Set terraform validation CLI options - https://www.terraform.io/docs/commands/validate.html
    - tf_validation_cli_options=""

    # Set terraform plan CLI options - https://www.terraform.io/docs/commands/plan.html
    - tf_plan_cli_options=" -lock=false -input=false"

    # Set terraform apply CLI options
    - tf_apply_cli_options=" -auto-approve -input=false"

# Install dependencies
before_install:
  # Download and install terraform before each run
  - wget https://releases.hashicorp.com/terraform/"$tf_version"/terraform_"$tf_version"_linux_amd64.zip
  - unzip terraform_"$tf_version"_linux_amd64.zip
  - sudo mv terraform /usr/local/bin/
  - rm terraform_"$tf_version"_linux_amd64.zip

jobs:
  include:
    - stage: terraform plan
      # Terraform Plan: As part of a pull request or kicked off by an API
      if: type IN (pull_request, api)
      script:
        - echo "Validating Terraform fmt"
        - terraform fmt -recursive -check
        - echo "Pull request detected, creating change plan"
        - terraform init $tf_init_cli_options
        - terraform validate $tf_validation_cli_options
        - terraform plan $tf_plan_cli_options
    - stage: terraform apply
      # Terraform Apply: When pushing direct to master, or when PR merge into master
      if: type IN (push) and branch = master
      script:
        - echo "Merge detected, executing changes"
        - terraform init $tf_init_cli_options
        - terraform apply $tf_apply_cli_options
